[profile.default]
src      = "contracts"
out      = "out"
libs     = []
solc     = "0.8.20"
optimizer        = true
optimizer_runs   = 200

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia   = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
